let companionProfile=null;try{const value=new URLSearchParams(location.hash.slice(1)).get('intro');if(value){const parsed=JSON.parse(value);if(typeof parsed.name==='string'&&typeof parsed.bio==='string')companionProfile={name:parsed.name.slice(0,80),bio:parsed.bio.slice(0,900)};}}catch{}
let ended=false,meeting=0,step=0,running=false,elapsed=0,started=0,quietEnd=0;const notes=sessions.map(()=>({entry:'',exit:''}));const $=id=>document.getElementById(id);const fmt=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
const songChoices=sessions.map(()=>({opening:"being-me.mp3",closing:"not-lost.mp3"}));
function stopAudio(){ $("songAudio").pause(); }
function render(){stopAudio();$("personalWelcome").hidden=!(meeting===0&&step===0&&companionProfile);$("companionName").textContent=companionProfile?"אני "+companionProfile.name:"";$("companionBio").textContent=companionProfile?companionProfile.bio:"";const m=sessions[meeting],s=m.stages[step],start=m.stages.slice(0,step).reduce((a,x)=>a+x.minutes,0);$('meetingLabel').textContent='מפגש '+(meeting+1)+' מתוך 6 · 60 דקות';$('sessionTitle').textContent=m.name;$('sessionSub').textContent=m.sub;$('range').textContent='דקות '+start+' עד '+(start+s.minutes)+' · '+s.minutes+' דקות';$('stageTitle').textContent=s.title;$('question').textContent=s.question;$('invitation').textContent=s.invitation;$('together').textContent=s.together;const musicKey=step===0?'opening':'closing';const showMusic=step===0||step===m.stages.length-1;$('musicPanel').hidden=!showMusic;$('musicHeading').textContent=step===0?'שיר פותח':'שיר סוגר';$('songSelect').value=songChoices[meeting][musicKey];const source=new URL('assets/'+$('songSelect').value,location.href).href;if($('songAudio').src!==source){$('songAudio').src=source;$('songAudio').load()}$('practicePanel').hidden=!s.practice;$('practicePanel').open=false;$('practiceOptions').replaceChildren();(s.practice||[]).forEach(([title,text])=>{const d=document.createElement('details'),h=document.createElement('summary'),p=document.createElement('p');h.textContent=title;p.textContent=text;d.append(h,p);$('practiceOptions').append(d)});$('prev').disabled=step===0;$('next').textContent=step===m.stages.length-1?'סיום המפגש':'לשלב הבא';$('steps').replaceChildren();m.stages.forEach((x,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.textContent=(i+1)+'. '+x.title+' · '+x.minutes+' דק׳';b.className=i===step?'active':'';b.setAttribute('aria-current',i===step?'step':'false');b.onclick=()=>{ended=false;step=i;stopQuiet();render();focusStage()};li.append(b);$('steps').append(li)});document.querySelectorAll('#sessions button').forEach((b,i)=>{b.className=i===meeting?'active':'';b.setAttribute('aria-pressed',i===meeting)});$('entry').value=notes[meeting].entry;$('exit').value=notes[meeting].exit;trace();}
function focusStage(){document.querySelector('.stage').focus({preventScroll:true});document.querySelector('.stage').scrollIntoView({block:'start'});} $('jump').onclick=focusStage;
function trace(){const n=notes[meeting];$('trace').textContent=n.entry?'כך הגעת: '+n.entry+(n.exit?'\nוזה מה שאת לוקחת: '+n.exit:'\nבסגירה אפשר לחזור למילים האלה, בלי לדרוש שמשהו השתנה.') : ''}
function tick(){const sec=elapsed+(running?Math.floor((Date.now()-started)/1000):0);$('elapsed').textContent=fmt(sec);$('timeNote').textContent=ended?'תודה על המפגש. קחי איתך את מה שמתאים לך.':sec>=3600?'השעה שלנו מסתיימת. ניקח רגע לאסוף ולהיפרד.':sec>=3120?'הזמן שנותר מוקדש לאיסוף ולסגירה.':'מתקדמות יחד, בקצב שלנו.';if(quietEnd){const left=Math.max(0,Math.ceil((quietEnd-Date.now())/1000));$('silenceText').textContent=left?'נותרו '+left+' שניות':'הדקה הסתיימה. מה את שמה לב עכשיו?';if(!left){quietEnd=0;$('silenceStop').hidden=true;}}}
function stopQuiet(){quietEnd=0;$('silenceText').textContent='';$('silenceStop').hidden=true;}
function pause(){if(running)elapsed+=Math.floor((Date.now()-started)/1000);running=false;$('timer').textContent='המשך שעון'}
sessions.forEach((m,i)=>{const b=document.createElement('button');b.textContent=m.name;b.onclick=()=>{if(running&&!confirm('מעבר למפגש אחר יאפס את שעון המפגש. לעבור?'))return;pause();ended=false;elapsed=0;meeting=i;step=0;stopQuiet();render();tick();$('timer').textContent='התחלת שעון'};$('sessions').append(b)});
$('timer').onclick=()=>{if(running)pause();else{started=Date.now();running=true;$('timer').textContent='השהיית שעון'}tick()};$('timerReset').onclick=()=>{if(confirm('לאפס את זמן המפגש?')){pause();elapsed=0;tick();$('timer').textContent='התחלת שעון'}};
$('prev').onclick=()=>{if(step>0){step--;stopQuiet();render();focusStage()}};$('next').onclick=()=>{if(step<sessions[meeting].stages.length-1){step++;stopQuiet();render();focusStage()}else{ended=true;stopAudio();pause();stopQuiet();$('timeNote').textContent='תודה על המפגש. קחי איתך את מה שמתאים לך.';$('next').textContent='המפגש נסגר';}};
$('silence').onclick=()=>{stopAudio();quietEnd=Date.now()+60000;$('silenceStop').hidden=false;tick();};$('silenceStop').onclick=stopQuiet;
['entry','exit'].forEach(id=>$(id).oninput=()=>{notes[meeting][id]=$(id).value;trace()});$('reset').onclick=()=>{if(confirm('לנקות את המילים מכל ששת המפגשים ולאפס את השעון?')){notes.forEach(n=>{n.entry='';n.exit=''});pause();ended=false;elapsed=0;meeting=0;step=0;stopQuiet();render();tick();$('timer').textContent='התחלת שעון'}};
$('songSelect').onchange=()=>{const key=step===0?'opening':'closing';songChoices[meeting][key]=$('songSelect').value;stopAudio();$('audioStatus').textContent='';$('songAudio').src='assets/'+$('songSelect').value;$('songAudio').load()};$('songAudio').onerror=()=>{$('audioStatus').textContent='השיר לא נטען. אפשר להמשיך ברגע שקט.'};$('songAudio').onloadedmetadata=()=>{$('audioStatus').textContent='אורך השיר: '+fmt(Math.round($('songAudio').duration))};setInterval(tick,250);render();tick();
