const musicLibrary=[{file:'alive.mp3',title:'לא הכול. ואני חיה.',mood:'להתעורר'},{file:'journey.mp3',title:'מה שווה כל הסיבוב הזה?',mood:'להעמיק'},{file:'not-lost.mp3',title:'לא הלכתי לאיבוד',mood:'להתרכך'},{file:'risk.mp3',title:'סיכון מחושב',mood:'להתעורר'},{file:'came-for-me.mp3',title:'באתי לקחת אותי',mood:'להעמיק'},{file:'all-ages.mp3',title:'בת כמה אני עכשיו? כולן.',mood:'להתרכך'}];
const blankLiving=()=>({word:'',landing:'',threads:['','',''],chosen:null,before:'',after:'',notice:'',next:'',other:'',open:''});
const livingStates=sessions.map(blankLiving),defaultSongs=sessions.map((_,i)=>({opening:musicLibrary[(i%2)*3+i%3].file,closing:musicLibrary[((i+1)%2)*3+(i+1)%3].file}));defaultSongs.forEach((x,i)=>Object.assign(songChoices[i],x));
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function btn(text,fn,cls){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b}
function field(label,value,fn){const l=el('label',label),x=el('input');x.value=value;x.maxLength=180;x.oninput=()=>fn(x.value);l.append(x);return l}
function livingIntro(title,text){const p=$('livingPanel');p.append(el('h3',title),el('p',text),el('small','מה שנכתב כאן גלוי לשתיכן. אפשר גם לדבר בלי לכתוב.'));return p}
function musicChoices(){const key=step===0?'opening':'closing',base=((meeting+(key==='closing'?1:0))%2)*3,options=musicLibrary.slice(base,base+3);$('songSelect').replaceChildren();$('songButtons').replaceChildren();options.forEach(t=>{const o=el('option',t.title);o.value=t.file;$('songSelect').append(o);const b=btn(t.mood,()=>{songChoices[meeting][key]=t.file;stopAudio();musicChoices()});b.append(el('small',t.title));b.setAttribute('aria-pressed',songChoices[meeting][key]===t.file);$('songButtons').append(b)});$('songSelect').value=songChoices[meeting][key];const url=new URL('assets/'+songChoices[meeting][key],location.href).href;if($('songAudio').src!==url){$('audioStatus').textContent='';$('songAudio').src=url;$('songAudio').load()}}
$('noMusic').onclick=()=>{stopAudio();$('audioStatus').textContent='נשארות יחד בשקט. אפשר לבחור שיר בהמשך.'};
function arrival(){const st=livingStates[meeting],p=livingIntro(meeting===0?'איך נעים לך להתחיל?':'רגע להגיע','את יכולה לבחור דרך להיכנס לרגע הזה. אפשר גם להמשיך ישר לשיחה.');const area=el('div',undefined,'arrival-field'),word=el('strong',st.word||'יש לי מקום כאן'),echo=el('p',st.landing);area.append(word,echo);p.append(area);const choices=el('div',undefined,'choice-row');[['מניחה רגליים','אפשר להרגיש את המגע עם הרצפה. קחי רגע, בקצב שלך.'],['מרווחת כתפיים','אם נעים לך, אפשר לשנות קצת תנוחה ולתת לכתפיים מקום.'],['פשוט נשארת','אין צורך לעשות דבר. אפשר להישאר כאן רגע יחד.']].forEach(([label,copy],i)=>{const b=btn(label,()=>{st.landing=copy;echo.textContent=copy;area.dataset.shape=i;choices.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x===b))});b.setAttribute('aria-pressed',st.landing===copy);choices.append(b)});p.append(choices,field('אם תרצי, מילה לאיך שאת כאן עכשיו',notes[meeting].entry,v=>{st.word=v;word.textContent=v||'יש לי מקום כאן';notes[meeting].entry=v;$('entry').value=v;trace()}))}
function focusBoard(){const st=livingStates[meeting],p=livingIntro('נותנות מקום לדבר אחד','אחרי ששיתפת, אילו מילים נשארות איתך? אפשר לכתוב עד שלוש ולבחור עם מה נישאר.');const fields=el('div',undefined,'focus-inputs'),board=el('div',undefined,'focus-board'),shelf=el('div',undefined,'focus-shelf');function draw(){board.replaceChildren(el('small',st.chosen===null?'בחרי מילה מהכרטיסים':'עם זה נשארות היום'));if(st.chosen!==null)board.append(el('strong',st.threads[st.chosen]));shelf.replaceChildren();st.threads.forEach((t,i)=>{if(t.trim()){const b=btn(t,()=>{st.chosen=i;draw()},st.chosen===i?'active':'');b.setAttribute('aria-pressed',st.chosen===i);shelf.append(b)}});if(st.chosen!==null)shelf.append(el('p','גם השאר קיבלו מקום. אפשר לחזור אליהם בהמשך.'))}st.threads.forEach((v,i)=>fields.append(field('מילה או משפט קצר '+(i+1),v,t=>{st.threads[i]=t;if(!t.trim()&&st.chosen===i)st.chosen=null;draw()})));p.append(fields,board,shelf);draw()}
function practice(){const st=livingStates[meeting],focus=st.chosen===null?'':st.threads[st.chosen],p=livingIntro('מהמילים אל רגע חי','נבחר אפשרות אחת. את יכולה לנסות, לשנות או להישאר בהקשבה.');if(focus)p.append(el('p','החוט שלנו: '+focus,'focus-reminder'));const tabs=el('div',undefined,'choice-row'),space=el('div',undefined,'practice-space');const modes=[['לומר בקול',()=>{space.append(field('מה את אומרת לעצמך ברגע הזה?',st.before,v=>st.before=v),field('יש משהו שתרצי לנסות לומר אחרת?',st.after,v=>st.after=v));const card=el('div',undefined,'spoken-card');space.append(btn('נותנת למילים קול',()=>{card.replaceChildren(el('strong',st.after||st.before||'עוד אין לי מילים.'));card.append(el('p','אם מתאים, קראי את המשפט בקול. אני כאן להקשיב.'))}),card)}],['לראות איפה עוד',()=>space.append(el('p',focus?'כאן: '+focus:'אפשר לחזור לרגע שהבאת.'),field('איפה עוד את פוגשת משהו דומה, אם בכלל?',st.other,v=>st.other=v),el('p','נניח את שני הרגעים זה לצד זה. מה דומה עבורך ומה שונה?'))],['לנסות תנועה',()=>{space.append(el('p','איזו תנועה קטנה מתאימה למה שאת רוצה עכשיו? אפשר להתרווח, להזיז יד או לשנות תנוחה. רק אם נעים לך.'));const response=el('p');space.append(btn('לוקחת רגע לנסות',()=>{response.className='spoken-card';response.textContent='המסך יכול לחכות. קחי את הזמן שלך, ואז חזרי לספר מה שמת לב.'}),response)}]];modes.forEach(([label,fn])=>{const b=btn(label,()=>{space.replaceChildren();fn();tabs.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x===b))});b.setAttribute('aria-pressed',false);tabs.append(b)});p.append(tabs,space,field('מה שמת לב שקרה? גם ״לא השתנה״ יכול להיות מדויק.',st.notice,v=>st.notice=v))}
function closing(){const st=livingStates[meeting],p=livingIntro(meeting===5?'מה נשאר איתך מהדרך?':'מה את לוקחת איתך?','נחזיר לכאן את המילים שלך. אין צורך להוכיח שמשהו השתנה.');const card=el('div',undefined,'take-card');function paint(){card.replaceChildren();[['כך הגעתי',notes[meeting].entry],['עם זה נשארתי',st.chosen===null?'':st.threads[st.chosen]],['משפט שניסיתי',st.after||st.before],['מה שמתי לב',st.notice],['אני לוקחת איתי',notes[meeting].exit],['רגע לחיים',st.next],['מה נשאר פתוח',st.open]].forEach(([label,value])=>{if(value){const row=el('div');row.append(el('small',label),el('p',value));card.append(row)}});if(!card.childNodes.length)card.append(el('p','אפשר לקחת משהו במילים, בשקט או במחברת שלך.'))}p.append(field('מה תרצי לקחת איתך?',notes[meeting].exit,v=>{notes[meeting].exit=v;$('exit').value=v;trace();paint()}),field(meeting===5?'מה יעזור לך לחזור לזה גם בהמשך?':'באיזה רגע בחיים תרצי לזכור את זה?',st.next,v=>{st.next=v;paint()}));if(meeting===5)p.append(field('מה נשאר פתוח, אם יש משהו כזה?',st.open,v=>{st.open=v;paint()}));p.append(card,btn('שמירת המילים שלי לקובץ',()=>{const blob=new Blob([sessions[meeting].name+'\n\n'+card.innerText],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='המילים-שלי-מפגש-'+(meeting+1)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}));paint()}
function livingRender(){musicChoices();const p=$('livingPanel');p.replaceChildren();p.hidden=false;const m=sessions[meeting],s=m.stages[step];if(step===0)arrival();else if(step===(meeting===0?3:meeting===5?1:2))focusBoard();else if(s.practice)practice();else if(step===m.stages.length-1)closing();else p.hidden=true;}
const baseRender=render;render=function(){baseRender();livingRender()};window.resetLiving=()=>{livingStates.forEach(st=>Object.assign(st,blankLiving()));defaultSongs.forEach((x,i)=>Object.assign(songChoices[i],x));};livingRender();
const paintLiving=livingRender;livingRender=function(){paintLiving();const active=!$('livingPanel').hidden;$('invitation').hidden=active;$('together').hidden=active;if(sessions[meeting].stages[step].practice)$('practicePanel').hidden=true;if(step===0){const st=livingStates[meeting];const copies=['אפשר להרגיש את המגע עם הרצפה. קחי רגע, בקצב שלך.','אם נעים לך, אפשר לשנות קצת תנוחה ולתת לכתפיים מקום.','אין צורך לעשות דבר. אפשר להישאר כאן רגע יחד.'];const i=copies.indexOf(st.landing);if(i>=0)document.querySelector('.arrival-field').dataset.shape=i;}};livingRender();
